---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite101-scc-storeuser
  labels:
    backstage.io/kubernetes-id: mywebsite101
    app.kubernetes.io/name: mywebsite101
    rht-gitops.com/janus-argocd: mywebsite101
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:margheproject:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite101-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: mywebsite101
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:margheproject:storeuseradmin-sa
